services:
  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    environment:
      GID: "${GID-1000}"
      COLLECTIONS: "crowdsecurity/linux crowdsecurity/traefik"
    volumes:
      - ./data/acquis.yaml:/etc/crowdsec/acquis.yaml
      - ./data/db:/var/lib/crowdsec/data/
      - ./data/config:/etc/crowdsec/
      - /root/traefik/logs:/var/log/traefik/:ro
    networks:
      - lan
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  bouncer-traefik:
    image: docker.io/fbonalair/traefik-crowdsec-bouncer:latest
    container_name: bouncer-traefik
    environment:
      CROWDSEC_BOUNCER_API_KEY: create_a_random_api_key
      CROWDSEC_AGENT_HOST: crowdsec:8080
    networks:
      - lan
    depends_on:
      - crowdsec
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

networks:
  lan:
    external: true
